
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/284/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-45-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/289/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-45-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/291/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.8.0-40-generic - x86_64
...
